travis:
  secure:
    BINSTAR_TOKEN: L+LHjijY5V5vT6/GM+/V0lnR97i4tQLke7dpA3AetswrFZomudVsfUUTNxZvcFRMy69SIhpIw2XLf1hLiYCTDn9hnRiHdpRfGULCfx3ZFKL3tKnwvs78pWQ1yLVN1FXtN6Ulm7bHJ8YNz1LL1zd4pIEHh3G74JdIcPjoMyIxSxQpLrQ7skdTZCNzWAaB4/+nq4falMzCh1PX6itIwzl3HVs3GKPriOkj3thEDxjS1zw7Iw6+EpMIfkF77SwLMXwE3WIfNeHFsAiYUHa3XT+g0JTdnvypjXlDIdoDt6oAvCx4R+oO4ddXaHj/RurM1d9gFxqWpHblVCF8x7Bpn4sxxFFxGTWrSfeUhZWMI1F1BRRYeOW5bqM2t0B6i3u3+JH1DjaYX0eamUP4EbDtLW+wdoyoD0bY36gHrMo3Ma2xGfRNH2XocI2me5nO1EnxZryPU8BSkcNfeT8knD0IPpft7UfqUmrB9X3sbn7Myw6DFS6VdE+GZsbhlT1zOYG0MWFLtqi3lxO5x02LE+KIkCdmSvS6O2O8XZckRMgtyIlmLqVEPHb/qm7gKahzjF1pyHOAUKjyg6mFDIbFF8qu0yjBUY9/Pei8phDuFzhlM+/NfP6OA6yJjIZELEk4u8lazMZWc1kt5hQSik9Krb/YAbwIPjnxZh2BD4WpgU1ul4RiQjY=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
