travis:
  secure:
    BINSTAR_TOKEN: kel4fw3g7VnO6eCsdDb/KOcHEBUxKa+3rlV2DEZM/yfU4nb02g3/Y7Bml5Rv5/14AHZk6eyiFjRplNb7jzt7O19z6aIizGRtJ1wGYzRZcv5nQFzSj8Y3ddGOLx2eVesbSZcDw0KjRbEywWfsoRD5QYlN3kpDu/HmnkG+CUwVFGuYKVkeXOHDnQbJZoSq+bxuRCXV2UftDtko4SYtB1vYyGuKjo+rwPFUynwH1p4rK+NLMN9IbhCW82L39++PDbuwkXbs4fh7RLWExeU4GrkQ68rGImcfknZnPmGTh7ujFtJCkeby6BtjJFyrW54gBFZbv0WWaU+GMy5+Nk2ZFHO/eN8QdD/Ce72jQCvZFc+i93VTGf4IHQ5bouwjVEdCgzxW2tedfPwYD8SJC+g1IbXMjPAbCHy5mhFktJCprkL3mV4qLyy+f4LyvqeAsodswkCXuwOExgd295TuJ+zyQYU7I7ZJrAJ+SeTLS52ANw2HB6wcaL92KGMKXsfqnduTzCEBMcudwV4YhLYx0KFgR8+GpIftIAvHQZC6c70e9b8anzWCu1HCXh76TBybDIoTvJB4RrmVuIYjcrHbQV19AzPLKhk7VvQ0oi1joAxpCYaCvp2SprHr44DzFtgtuvqqQKYfXIcIPyYh17Hdi6eAjPIvKr+xXIojuazX7ah6TxoAP8A=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
